// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":false,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"HauntIslandMenu","status":true,"description":"Game-specific in-game menu for Haunt: Island, overrides default game menu.","parameters":{"Starting Corruption":"0.0","Starting Insight":"0.0","Trait Gauge Color 1":"#4B87BA","Trait Gauge Color 2":"#FFFFFF","Charlotte Story Texts":"[\"\\\"Yada yada yada\\\\nblah blah blah\\\\nstuff stuff stuff\\\"\"]","Henrik Story Texts":"","Charlotte Story Pictures":"[\"Actor1_4\"]","Henrik Story Pictures":""}}
];
